### ISSUE TITLE
Add source code URI to rubygems.org

### ISSUE THREAD

**Issue by nirvdrum** [banister/method_source#41]
The gem metadata on rubygems.org doesn't set the source code URI, so there's no easy way to jump from the gem to its source repo. I had to search on GitHub and then compare the list of release tags to the set of versions on rubygems.org to verify I found the correct repo.

If someone with permissions could add the value to rubygems.org, that would be greatly appreciated.

**Comment by banister** [comment]
added, let me know if it appears for you

**Comment by nirvdrum** [comment]
Looks good. Thanks for the quick turnaround!

**Comment by lanzhiheng** [comment]
I think some issue should be close if it have been fixed. like [44](https://github.com/banister/method_source/issues/44)

**Comment by nirvdrum** [comment]
I normally let the person performing the fix close it out. But I can do so.
