### ISSUE TITLE
Bacon to replace to RSpec or Minitest

### ISSUE THREAD

**Issue by junaruga** [banister/method_source#43]
Hi @banister 

When I talked with the author of `bacon` by email, he told me that Bacon development had halted.
https://github.com/chneukirchen/bacon/issues

I want to replace `bacon` that is used for `method_source` to RSpec 3 or Minitest.

How do you think?

**Comment by banister** [comment]
@junaruga sounds great if you have the energy for it :)

**Comment by junaruga** [comment]
@banister ok I will try and send PR for that :)

**Comment by junaruga** [comment]
I can spend a time for that from today. I will proceed this.
